CREATE TABLE IF NOT EXISTS template_analysis_sessions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    session_key VARCHAR(128) NOT NULL,
    owner_user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'running',
    current_phase VARCHAR(64) NOT NULL DEFAULT 'idle',
    status_message VARCHAR(512) NULL,
    template_name VARCHAR(255) NULL,
    vision_model VARCHAR(128) NULL,
    planner_model VARCHAR(128) NULL,
    mode VARCHAR(64) NULL,
    vision_status VARCHAR(255) NULL,
    params_json JSON NULL,
    result_json JSON NULL,
    billing_json JSON NULL,
    last_error_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    UNIQUE KEY uq_template_analysis_sessions_key (session_key),
    KEY idx_template_analysis_sessions_owner_status (owner_user_id, status),
    KEY idx_template_analysis_sessions_owner_updated (owner_user_id, updated_at),
    CONSTRAINT fk_template_analysis_sessions_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
